// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/grpchandler/proto/handler.proto

package handlerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersonaService_HandleStream_FullMethodName = "/rick.handler.v1.PersonaService/HandleStream"
)

// PersonaServiceClient is the client API for PersonaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PersonaService allows external systems to register as event handlers
// in Rick's choreography chain. The bidirectional stream serves as both
// the registration mechanism and the dispatch channel.
//
// Lifecycle:
//  1. Client opens stream, sends HandlerRegistration as first message
//  2. Server responds with RegistrationAck
//  3. Server sends DispatchRequest when trigger conditions are met
//  4. Client processes and sends HandlerResult back
//  5. Stream close = handler deregistration (automatic cleanup)
type PersonaServiceClient interface {
	HandleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandlerMessage, DispatchMessage], error)
}

type personaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonaServiceClient(cc grpc.ClientConnInterface) PersonaServiceClient {
	return &personaServiceClient{cc}
}

func (c *personaServiceClient) HandleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandlerMessage, DispatchMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PersonaService_ServiceDesc.Streams[0], PersonaService_HandleStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandlerMessage, DispatchMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersonaService_HandleStreamClient = grpc.BidiStreamingClient[HandlerMessage, DispatchMessage]

// PersonaServiceServer is the server API for PersonaService service.
// All implementations must embed UnimplementedPersonaServiceServer
// for forward compatibility.
//
// PersonaService allows external systems to register as event handlers
// in Rick's choreography chain. The bidirectional stream serves as both
// the registration mechanism and the dispatch channel.
//
// Lifecycle:
//  1. Client opens stream, sends HandlerRegistration as first message
//  2. Server responds with RegistrationAck
//  3. Server sends DispatchRequest when trigger conditions are met
//  4. Client processes and sends HandlerResult back
//  5. Stream close = handler deregistration (automatic cleanup)
type PersonaServiceServer interface {
	HandleStream(grpc.BidiStreamingServer[HandlerMessage, DispatchMessage]) error
	mustEmbedUnimplementedPersonaServiceServer()
}

// UnimplementedPersonaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersonaServiceServer struct{}

func (UnimplementedPersonaServiceServer) HandleStream(grpc.BidiStreamingServer[HandlerMessage, DispatchMessage]) error {
	return status.Error(codes.Unimplemented, "method HandleStream not implemented")
}
func (UnimplementedPersonaServiceServer) mustEmbedUnimplementedPersonaServiceServer() {}
func (UnimplementedPersonaServiceServer) testEmbeddedByValue()                        {}

// UnsafePersonaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonaServiceServer will
// result in compilation errors.
type UnsafePersonaServiceServer interface {
	mustEmbedUnimplementedPersonaServiceServer()
}

func RegisterPersonaServiceServer(s grpc.ServiceRegistrar, srv PersonaServiceServer) {
	// If the following call panics, it indicates UnimplementedPersonaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersonaService_ServiceDesc, srv)
}

func _PersonaService_HandleStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PersonaServiceServer).HandleStream(&grpc.GenericServerStream[HandlerMessage, DispatchMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersonaService_HandleStreamServer = grpc.BidiStreamingServer[HandlerMessage, DispatchMessage]

// PersonaService_ServiceDesc is the grpc.ServiceDesc for PersonaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersonaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rick.handler.v1.PersonaService",
	HandlerType: (*PersonaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleStream",
			Handler:       _PersonaService_HandleStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpchandler/proto/handler.proto",
}
