// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/grpchandler/proto/handler.proto

package handlerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HandlerMessage_Registration
	//	*HandlerMessage_Result
	//	*HandlerMessage_Heartbeat
	//	*HandlerMessage_Inject
	//	*HandlerMessage_Watch
	//	*HandlerMessage_Unwatch
	//	*HandlerMessage_RegisterWorkflow
	Msg           isHandlerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerMessage) Reset() {
	*x = HandlerMessage{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerMessage) ProtoMessage() {}

func (x *HandlerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerMessage.ProtoReflect.Descriptor instead.
func (*HandlerMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerMessage) GetMsg() isHandlerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HandlerMessage) GetRegistration() *HandlerRegistration {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *HandlerMessage) GetResult() *HandlerResult {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *HandlerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *HandlerMessage) GetInject() *InjectEventRequest {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Inject); ok {
			return x.Inject
		}
	}
	return nil
}

func (x *HandlerMessage) GetWatch() *WatchRequest {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Watch); ok {
			return x.Watch
		}
	}
	return nil
}

func (x *HandlerMessage) GetUnwatch() *UnwatchRequest {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_Unwatch); ok {
			return x.Unwatch
		}
	}
	return nil
}

func (x *HandlerMessage) GetRegisterWorkflow() *RegisterWorkflowRequest {
	if x != nil {
		if x, ok := x.Msg.(*HandlerMessage_RegisterWorkflow); ok {
			return x.RegisterWorkflow
		}
	}
	return nil
}

type isHandlerMessage_Msg interface {
	isHandlerMessage_Msg()
}

type HandlerMessage_Registration struct {
	Registration *HandlerRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type HandlerMessage_Result struct {
	Result *HandlerResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type HandlerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type HandlerMessage_Inject struct {
	Inject *InjectEventRequest `protobuf:"bytes,4,opt,name=inject,proto3,oneof"`
}

type HandlerMessage_Watch struct {
	Watch *WatchRequest `protobuf:"bytes,5,opt,name=watch,proto3,oneof"`
}

type HandlerMessage_Unwatch struct {
	Unwatch *UnwatchRequest `protobuf:"bytes,6,opt,name=unwatch,proto3,oneof"`
}

type HandlerMessage_RegisterWorkflow struct {
	RegisterWorkflow *RegisterWorkflowRequest `protobuf:"bytes,7,opt,name=register_workflow,json=registerWorkflow,proto3,oneof"`
}

func (*HandlerMessage_Registration) isHandlerMessage_Msg() {}

func (*HandlerMessage_Result) isHandlerMessage_Msg() {}

func (*HandlerMessage_Heartbeat) isHandlerMessage_Msg() {}

func (*HandlerMessage_Inject) isHandlerMessage_Msg() {}

func (*HandlerMessage_Watch) isHandlerMessage_Msg() {}

func (*HandlerMessage_Unwatch) isHandlerMessage_Msg() {}

func (*HandlerMessage_RegisterWorkflow) isHandlerMessage_Msg() {}

// HandlerRegistration is the first message a client sends to register
// itself as a handler in Rick's choreography chain.
type HandlerRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique handler name (e.g., "frontend-enricher", "security-scanner").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Event types this handler subscribes to (e.g., "persona.completed").
	EventTypes []string `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// Join condition: handler fires only after all listed personas have
	// completed for the same correlation. Empty = no join condition.
	AfterPersonas []string `protobuf:"bytes,3,rep,name=after_personas,json=afterPersonas,proto3" json:"after_personas,omitempty"`
	// Before-hook targets: personas that should wait for this handler
	// before dispatching. E.g., ["developer"] means developer won't fire
	// until this handler completes.
	BeforeHookTargets []string `protobuf:"bytes,4,rep,name=before_hook_targets,json=beforeHookTargets,proto3" json:"before_hook_targets,omitempty"`
	// If true, this handler supports two-phase hint/execute dispatch.
	// The server will register a gRPCHinter proxy so PersonaRunner sends
	// a hint_only=true DispatchRequest before the full Handle() dispatch.
	SupportsHints bool `protobuf:"varint,5,opt,name=supports_hints,json=supportsHints,proto3" json:"supports_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerRegistration) Reset() {
	*x = HandlerRegistration{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRegistration) ProtoMessage() {}

func (x *HandlerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRegistration.ProtoReflect.Descriptor instead.
func (*HandlerRegistration) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandlerRegistration) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *HandlerRegistration) GetAfterPersonas() []string {
	if x != nil {
		return x.AfterPersonas
	}
	return nil
}

func (x *HandlerRegistration) GetBeforeHookTargets() []string {
	if x != nil {
		return x.BeforeHookTargets
	}
	return nil
}

func (x *HandlerRegistration) GetSupportsHints() bool {
	if x != nil {
		return x.SupportsHints
	}
	return false
}

// HandlerResult is the client's response to a DispatchRequest.
type HandlerResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches DispatchRequest.dispatch_id for correlation.
	DispatchId string `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	// Result events to emit (enrichment context, AI responses, etc.).
	Events []*EventEnvelope `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Non-empty = handler failed. PersonaRunner emits PersonaFailed.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// When true, handler ran successfully but has more work to do.
	// PersonaRunner persists result events but skips PersonaCompleted.
	Incomplete    bool `protobuf:"varint,4,opt,name=incomplete,proto3" json:"incomplete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerResult) Reset() {
	*x = HandlerResult{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerResult) ProtoMessage() {}

func (x *HandlerResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerResult.ProtoReflect.Descriptor instead.
func (*HandlerResult) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{2}
}

func (x *HandlerResult) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *HandlerResult) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *HandlerResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandlerResult) GetIncomplete() bool {
	if x != nil {
		return x.Incomplete
	}
	return false
}

// Heartbeat keeps the stream alive during long idle periods.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type DispatchMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DispatchMessage_Ack
	//	*DispatchMessage_Dispatch
	//	*DispatchMessage_InjectResult
	//	*DispatchMessage_Notification
	//	*DispatchMessage_WorkflowResult
	//	*DispatchMessage_Displaced
	Msg           isDispatchMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchMessage) Reset() {
	*x = DispatchMessage{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessage) ProtoMessage() {}

func (x *DispatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessage.ProtoReflect.Descriptor instead.
func (*DispatchMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchMessage) GetMsg() isDispatchMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DispatchMessage) GetAck() *RegistrationAck {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *DispatchMessage) GetDispatch() *DispatchRequest {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *DispatchMessage) GetInjectResult() *InjectEventResult {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_InjectResult); ok {
			return x.InjectResult
		}
	}
	return nil
}

func (x *DispatchMessage) GetNotification() *WorkflowNotification {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *DispatchMessage) GetWorkflowResult() *RegisterWorkflowResult {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_WorkflowResult); ok {
			return x.WorkflowResult
		}
	}
	return nil
}

func (x *DispatchMessage) GetDisplaced() *DisplacedNotification {
	if x != nil {
		if x, ok := x.Msg.(*DispatchMessage_Displaced); ok {
			return x.Displaced
		}
	}
	return nil
}

type isDispatchMessage_Msg interface {
	isDispatchMessage_Msg()
}

type DispatchMessage_Ack struct {
	Ack *RegistrationAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type DispatchMessage_Dispatch struct {
	Dispatch *DispatchRequest `protobuf:"bytes,2,opt,name=dispatch,proto3,oneof"`
}

type DispatchMessage_InjectResult struct {
	InjectResult *InjectEventResult `protobuf:"bytes,3,opt,name=inject_result,json=injectResult,proto3,oneof"`
}

type DispatchMessage_Notification struct {
	Notification *WorkflowNotification `protobuf:"bytes,4,opt,name=notification,proto3,oneof"`
}

type DispatchMessage_WorkflowResult struct {
	WorkflowResult *RegisterWorkflowResult `protobuf:"bytes,5,opt,name=workflow_result,json=workflowResult,proto3,oneof"`
}

type DispatchMessage_Displaced struct {
	Displaced *DisplacedNotification `protobuf:"bytes,6,opt,name=displaced,proto3,oneof"`
}

func (*DispatchMessage_Ack) isDispatchMessage_Msg() {}

func (*DispatchMessage_Dispatch) isDispatchMessage_Msg() {}

func (*DispatchMessage_InjectResult) isDispatchMessage_Msg() {}

func (*DispatchMessage_Notification) isDispatchMessage_Msg() {}

func (*DispatchMessage_WorkflowResult) isDispatchMessage_Msg() {}

func (*DispatchMessage_Displaced) isDispatchMessage_Msg() {}

// DisplacedNotification is sent by the server when a new client registers
// with the same handler name, displacing this client's stream. The client
// should treat this as a terminal error and reconnect after backoff.
type DisplacedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       string                 `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"` // the handler name that was displaced
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`   // human-readable reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplacedNotification) Reset() {
	*x = DisplacedNotification{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplacedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplacedNotification) ProtoMessage() {}

func (x *DisplacedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplacedNotification.ProtoReflect.Descriptor instead.
func (*DisplacedNotification) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{5}
}

func (x *DisplacedNotification) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *DisplacedNotification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RegistrationAck confirms successful handler registration.
type RegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ok" or error description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationAck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistrationAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DispatchRequest sends an event to the external handler for processing.
type DispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique dispatch ID for correlating the result.
	DispatchId string `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	// The triggering event.
	Event *EventEnvelope `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// If true, handler should return a HintEmitted event (lightweight pre-check)
	// instead of full execution results. Backwards compatible: handlers that
	// don't understand this flag run fully (PersonaRunner treats result as hint).
	HintOnly      bool `protobuf:"varint,3,opt,name=hint_only,json=hintOnly,proto3" json:"hint_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *DispatchRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DispatchRequest) GetHintOnly() bool {
	if x != nil {
		return x.HintOnly
	}
	return false
}

// InjectEventRequest allows an external system to push an event into a
// Rick workflow through the existing bidirectional stream.
type InjectEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated ID to correlate the response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The event to inject. Required fields: type, correlation_id, payload.
	// Server assigns: id, aggregate_id, version, timestamp, source.
	Event         *EventEnvelope `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectEventRequest) Reset() {
	*x = InjectEventRequest{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectEventRequest) ProtoMessage() {}

func (x *InjectEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectEventRequest.ProtoReflect.Descriptor instead.
func (*InjectEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{8}
}

func (x *InjectEventRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InjectEventRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

// InjectEventResult is the server's response to an InjectEventRequest.
type InjectEventResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches InjectEventRequest.request_id.
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                    // non-empty on failure
	EventId       string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // server-assigned event ID on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectEventResult) Reset() {
	*x = InjectEventResult{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectEventResult) ProtoMessage() {}

func (x *InjectEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectEventResult.ProtoReflect.Descriptor instead.
func (*InjectEventResult) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{9}
}

func (x *InjectEventResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InjectEventResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InjectEventResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InjectEventResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// RegisterWorkflowRequest registers a custom workflow definition. The workflow
// is a completion manifest — it declares which handlers must emit
// PersonaCompleted for the workflow to succeed. Ordering emerges from handler
// trigger declarations, not from this definition.
type RegisterWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated ID to correlate the response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Unique workflow identifier (e.g., "my-review", "ci-pipeline").
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Handler names that must all emit PersonaCompleted.
	// Can reference local handlers, other gRPC handlers, or the registering
	// handler itself — any handler currently subscribed is eligible.
	Required []string `protobuf:"bytes,3,rep,name=required,proto3" json:"required,omitempty"`
	// Max feedback loop iterations (0 = use server default of 3).
	MaxIterations int32 `protobuf:"varint,4,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	// If true, pause instead of fail when max iterations reached.
	EscalateOnMaxIter bool `protobuf:"varint,5,opt,name=escalate_on_max_iter,json=escalateOnMaxIter,proto3" json:"escalate_on_max_iter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterWorkflowRequest) Reset() {
	*x = RegisterWorkflowRequest{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowRequest) ProtoMessage() {}

func (x *RegisterWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterWorkflowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *RegisterWorkflowRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *RegisterWorkflowRequest) GetEscalateOnMaxIter() bool {
	if x != nil {
		return x.EscalateOnMaxIter
	}
	return false
}

// RegisterWorkflowResult is the server's response to a RegisterWorkflowRequest.
type RegisterWorkflowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches RegisterWorkflowRequest.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // non-empty on failure
	// Handler names from the required list that are currently registered
	// (local or gRPC-connected). Handlers not in this list may connect later.
	AvailableHandlers []string `protobuf:"bytes,4,rep,name=available_handlers,json=availableHandlers,proto3" json:"available_handlers,omitempty"`
	// Handler names from the required list that are NOT currently registered.
	MissingHandlers []string `protobuf:"bytes,5,rep,name=missing_handlers,json=missingHandlers,proto3" json:"missing_handlers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterWorkflowResult) Reset() {
	*x = RegisterWorkflowResult{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowResult) ProtoMessage() {}

func (x *RegisterWorkflowResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowResult.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowResult) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterWorkflowResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegisterWorkflowResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkflowResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterWorkflowResult) GetAvailableHandlers() []string {
	if x != nil {
		return x.AvailableHandlers
	}
	return nil
}

func (x *RegisterWorkflowResult) GetMissingHandlers() []string {
	if x != nil {
		return x.MissingHandlers
	}
	return nil
}

// WatchRequest subscribes to workflow lifecycle notifications for the given
// correlation IDs. An empty list means watch all workflows.
type WatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationIds []string               `protobuf:"bytes,1,rep,name=correlation_ids,json=correlationIds,proto3" json:"correlation_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{12}
}

func (x *WatchRequest) GetCorrelationIds() []string {
	if x != nil {
		return x.CorrelationIds
	}
	return nil
}

// UnwatchRequest unsubscribes from workflow lifecycle notifications for the
// given correlation IDs. An empty list means unwatch all.
type UnwatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationIds []string               `protobuf:"bytes,1,rep,name=correlation_ids,json=correlationIds,proto3" json:"correlation_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnwatchRequest) Reset() {
	*x = UnwatchRequest{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwatchRequest) ProtoMessage() {}

func (x *UnwatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwatchRequest.ProtoReflect.Descriptor instead.
func (*UnwatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{13}
}

func (x *UnwatchRequest) GetCorrelationIds() []string {
	if x != nil {
		return x.CorrelationIds
	}
	return nil
}

// WorkflowNotification is a push notification sent when a workflow reaches a
// terminal state (completed, failed, cancelled).
type WorkflowNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId   string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                              // "completed", "failed", "cancelled"
	Result          string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                              // completion result or fail/cancel reason
	FailedPhase     string                 `protobuf:"bytes,4,opt,name=failed_phase,json=failedPhase,proto3" json:"failed_phase,omitempty"` // phase that caused failure (empty if completed)
	StartedAtMs     int64                  `protobuf:"varint,5,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	CompletedAtMs   int64                  `protobuf:"varint,6,opt,name=completed_at_ms,json=completedAtMs,proto3" json:"completed_at_ms,omitempty"`
	DurationMs      int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TotalTokens     int32                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TokensByPhase   map[string]int32       `protobuf:"bytes,9,rep,name=tokens_by_phase,json=tokensByPhase,proto3" json:"tokens_by_phase,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TokensByBackend map[string]int32       `protobuf:"bytes,10,rep,name=tokens_by_backend,json=tokensByBackend,proto3" json:"tokens_by_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Phases          []*PhaseSummary        `protobuf:"bytes,11,rep,name=phases,proto3" json:"phases,omitempty"`
	Verdicts        []*VerdictDetail       `protobuf:"bytes,12,rep,name=verdicts,proto3" json:"verdicts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowNotification) Reset() {
	*x = WorkflowNotification{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNotification) ProtoMessage() {}

func (x *WorkflowNotification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNotification.ProtoReflect.Descriptor instead.
func (*WorkflowNotification) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{14}
}

func (x *WorkflowNotification) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *WorkflowNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowNotification) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WorkflowNotification) GetFailedPhase() string {
	if x != nil {
		return x.FailedPhase
	}
	return ""
}

func (x *WorkflowNotification) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *WorkflowNotification) GetCompletedAtMs() int64 {
	if x != nil {
		return x.CompletedAtMs
	}
	return 0
}

func (x *WorkflowNotification) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *WorkflowNotification) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *WorkflowNotification) GetTokensByPhase() map[string]int32 {
	if x != nil {
		return x.TokensByPhase
	}
	return nil
}

func (x *WorkflowNotification) GetTokensByBackend() map[string]int32 {
	if x != nil {
		return x.TokensByBackend
	}
	return nil
}

func (x *WorkflowNotification) GetPhases() []*PhaseSummary {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *WorkflowNotification) GetVerdicts() []*VerdictDetail {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

// PhaseSummary provides per-phase timing and status in a WorkflowNotification.
type PhaseSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "done", "failed"
	Iterations    int32                  `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseSummary) Reset() {
	*x = PhaseSummary{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseSummary) ProtoMessage() {}

func (x *PhaseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseSummary.ProtoReflect.Descriptor instead.
func (*PhaseSummary) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{15}
}

func (x *PhaseSummary) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PhaseSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PhaseSummary) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *PhaseSummary) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// VerdictDetail provides per-phase review verdict data in a WorkflowNotification.
type VerdictDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`                                // target phase ("develop")
	SourcePhase   string                 `protobuf:"bytes,2,opt,name=source_phase,json=sourcePhase,proto3" json:"source_phase,omitempty"` // who rendered it ("review", "qa")
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`                            // "pass", "fail", "unknown"
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Issues        []*IssueSummary        `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerdictDetail) Reset() {
	*x = VerdictDetail{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictDetail) ProtoMessage() {}

func (x *VerdictDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictDetail.ProtoReflect.Descriptor instead.
func (*VerdictDetail) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{16}
}

func (x *VerdictDetail) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *VerdictDetail) GetSourcePhase() string {
	if x != nil {
		return x.SourcePhase
	}
	return ""
}

func (x *VerdictDetail) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *VerdictDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *VerdictDetail) GetIssues() []*IssueSummary {
	if x != nil {
		return x.Issues
	}
	return nil
}

// IssueSummary is a single review finding in a VerdictDetail.
type IssueSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	File          string                 `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSummary) Reset() {
	*x = IssueSummary{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSummary) ProtoMessage() {}

func (x *IssueSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSummary.ProtoReflect.Descriptor instead.
func (*IssueSummary) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{17}
}

func (x *IssueSummary) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *IssueSummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IssueSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IssueSummary) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *IssueSummary) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

// EventEnvelope mirrors event.Envelope for wire transport.
type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	CausationId   string                 `protobuf:"bytes,7,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpchandler_proto_handler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_grpchandler_proto_handler_proto_rawDescGZIP(), []int{18}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *EventEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventEnvelope) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *EventEnvelope) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_grpchandler_proto_handler_proto protoreflect.FileDescriptor

const file_internal_grpchandler_proto_handler_proto_rawDesc = "" +
	"\n" +
	"(internal/grpchandler/proto/handler.proto\x12\x0frick.handler.v1\"\xe5\x03\n" +
	"\x0eHandlerMessage\x12J\n" +
	"\fregistration\x18\x01 \x01(\v2$.rick.handler.v1.HandlerRegistrationH\x00R\fregistration\x128\n" +
	"\x06result\x18\x02 \x01(\v2\x1e.rick.handler.v1.HandlerResultH\x00R\x06result\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.rick.handler.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\x06inject\x18\x04 \x01(\v2#.rick.handler.v1.InjectEventRequestH\x00R\x06inject\x125\n" +
	"\x05watch\x18\x05 \x01(\v2\x1d.rick.handler.v1.WatchRequestH\x00R\x05watch\x12;\n" +
	"\aunwatch\x18\x06 \x01(\v2\x1f.rick.handler.v1.UnwatchRequestH\x00R\aunwatch\x12W\n" +
	"\x11register_workflow\x18\a \x01(\v2(.rick.handler.v1.RegisterWorkflowRequestH\x00R\x10registerWorkflowB\x05\n" +
	"\x03msg\"\xc8\x01\n" +
	"\x13HandlerRegistration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12%\n" +
	"\x0eafter_personas\x18\x03 \x03(\tR\rafterPersonas\x12.\n" +
	"\x13before_hook_targets\x18\x04 \x03(\tR\x11beforeHookTargets\x12%\n" +
	"\x0esupports_hints\x18\x05 \x01(\bR\rsupportsHints\"\x9e\x01\n" +
	"\rHandlerResult\x12\x1f\n" +
	"\vdispatch_id\x18\x01 \x01(\tR\n" +
	"dispatchId\x126\n" +
	"\x06events\x18\x02 \x03(\v2\x1e.rick.handler.v1.EventEnvelopeR\x06events\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"incomplete\x18\x04 \x01(\bR\n" +
	"incomplete\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xc2\x03\n" +
	"\x0fDispatchMessage\x124\n" +
	"\x03ack\x18\x01 \x01(\v2 .rick.handler.v1.RegistrationAckH\x00R\x03ack\x12>\n" +
	"\bdispatch\x18\x02 \x01(\v2 .rick.handler.v1.DispatchRequestH\x00R\bdispatch\x12I\n" +
	"\rinject_result\x18\x03 \x01(\v2\".rick.handler.v1.InjectEventResultH\x00R\finjectResult\x12K\n" +
	"\fnotification\x18\x04 \x01(\v2%.rick.handler.v1.WorkflowNotificationH\x00R\fnotification\x12R\n" +
	"\x0fworkflow_result\x18\x05 \x01(\v2'.rick.handler.v1.RegisterWorkflowResultH\x00R\x0eworkflowResult\x12F\n" +
	"\tdisplaced\x18\x06 \x01(\v2&.rick.handler.v1.DisplacedNotificationH\x00R\tdisplacedB\x05\n" +
	"\x03msg\"I\n" +
	"\x15DisplacedNotification\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\tR\ahandler\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\x0fRegistrationAck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x85\x01\n" +
	"\x0fDispatchRequest\x12\x1f\n" +
	"\vdispatch_id\x18\x01 \x01(\tR\n" +
	"dispatchId\x124\n" +
	"\x05event\x18\x02 \x01(\v2\x1e.rick.handler.v1.EventEnvelopeR\x05event\x12\x1b\n" +
	"\thint_only\x18\x03 \x01(\bR\bhintOnly\"i\n" +
	"\x12InjectEventRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x05event\x18\x02 \x01(\v2\x1e.rick.handler.v1.EventEnvelopeR\x05event\"}\n" +
	"\x11InjectEventResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\"\xcd\x01\n" +
	"\x17RegisterWorkflowRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x1a\n" +
	"\brequired\x18\x03 \x03(\tR\brequired\x12%\n" +
	"\x0emax_iterations\x18\x04 \x01(\x05R\rmaxIterations\x12/\n" +
	"\x14escalate_on_max_iter\x18\x05 \x01(\bR\x11escalateOnMaxIter\"\xc1\x01\n" +
	"\x16RegisterWorkflowResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12-\n" +
	"\x12available_handlers\x18\x04 \x03(\tR\x11availableHandlers\x12)\n" +
	"\x10missing_handlers\x18\x05 \x03(\tR\x0fmissingHandlers\"7\n" +
	"\fWatchRequest\x12'\n" +
	"\x0fcorrelation_ids\x18\x01 \x03(\tR\x0ecorrelationIds\"9\n" +
	"\x0eUnwatchRequest\x12'\n" +
	"\x0fcorrelation_ids\x18\x01 \x03(\tR\x0ecorrelationIds\"\xe3\x05\n" +
	"\x14WorkflowNotification\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12!\n" +
	"\ffailed_phase\x18\x04 \x01(\tR\vfailedPhase\x12\"\n" +
	"\rstarted_at_ms\x18\x05 \x01(\x03R\vstartedAtMs\x12&\n" +
	"\x0fcompleted_at_ms\x18\x06 \x01(\x03R\rcompletedAtMs\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x05R\vtotalTokens\x12`\n" +
	"\x0ftokens_by_phase\x18\t \x03(\v28.rick.handler.v1.WorkflowNotification.TokensByPhaseEntryR\rtokensByPhase\x12f\n" +
	"\x11tokens_by_backend\x18\n" +
	" \x03(\v2:.rick.handler.v1.WorkflowNotification.TokensByBackendEntryR\x0ftokensByBackend\x125\n" +
	"\x06phases\x18\v \x03(\v2\x1d.rick.handler.v1.PhaseSummaryR\x06phases\x12:\n" +
	"\bverdicts\x18\f \x03(\v2\x1e.rick.handler.v1.VerdictDetailR\bverdicts\x1a@\n" +
	"\x12TokensByPhaseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aB\n" +
	"\x14TokensByBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"}\n" +
	"\fPhaseSummary\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\x05R\n" +
	"iterations\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xb3\x01\n" +
	"\rVerdictDetail\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12!\n" +
	"\fsource_phase\x18\x02 \x01(\tR\vsourcePhase\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x125\n" +
	"\x06issues\x18\x05 \x03(\v2\x1d.rick.handler.v1.IssueSummaryR\x06issues\"\x90\x01\n" +
	"\fIssueSummary\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x05 \x01(\x05R\x04line\"\xb6\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12!\n" +
	"\fcausation_id\x18\a \x01(\tR\vcausationId\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload2g\n" +
	"\x0ePersonaService\x12U\n" +
	"\fHandleStream\x12\x1f.rick.handler.v1.HandlerMessage\x1a .rick.handler.v1.DispatchMessage(\x010\x01BWZUgithub.com/marconn/rick-event-driven-development/internal/grpchandler/proto;handlerpbb\x06proto3"

var (
	file_internal_grpchandler_proto_handler_proto_rawDescOnce sync.Once
	file_internal_grpchandler_proto_handler_proto_rawDescData []byte
)

func file_internal_grpchandler_proto_handler_proto_rawDescGZIP() []byte {
	file_internal_grpchandler_proto_handler_proto_rawDescOnce.Do(func() {
		file_internal_grpchandler_proto_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpchandler_proto_handler_proto_rawDesc), len(file_internal_grpchandler_proto_handler_proto_rawDesc)))
	})
	return file_internal_grpchandler_proto_handler_proto_rawDescData
}

var file_internal_grpchandler_proto_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_grpchandler_proto_handler_proto_goTypes = []any{
	(*HandlerMessage)(nil),          // 0: rick.handler.v1.HandlerMessage
	(*HandlerRegistration)(nil),     // 1: rick.handler.v1.HandlerRegistration
	(*HandlerResult)(nil),           // 2: rick.handler.v1.HandlerResult
	(*Heartbeat)(nil),               // 3: rick.handler.v1.Heartbeat
	(*DispatchMessage)(nil),         // 4: rick.handler.v1.DispatchMessage
	(*DisplacedNotification)(nil),   // 5: rick.handler.v1.DisplacedNotification
	(*RegistrationAck)(nil),         // 6: rick.handler.v1.RegistrationAck
	(*DispatchRequest)(nil),         // 7: rick.handler.v1.DispatchRequest
	(*InjectEventRequest)(nil),      // 8: rick.handler.v1.InjectEventRequest
	(*InjectEventResult)(nil),       // 9: rick.handler.v1.InjectEventResult
	(*RegisterWorkflowRequest)(nil), // 10: rick.handler.v1.RegisterWorkflowRequest
	(*RegisterWorkflowResult)(nil),  // 11: rick.handler.v1.RegisterWorkflowResult
	(*WatchRequest)(nil),            // 12: rick.handler.v1.WatchRequest
	(*UnwatchRequest)(nil),          // 13: rick.handler.v1.UnwatchRequest
	(*WorkflowNotification)(nil),    // 14: rick.handler.v1.WorkflowNotification
	(*PhaseSummary)(nil),            // 15: rick.handler.v1.PhaseSummary
	(*VerdictDetail)(nil),           // 16: rick.handler.v1.VerdictDetail
	(*IssueSummary)(nil),            // 17: rick.handler.v1.IssueSummary
	(*EventEnvelope)(nil),           // 18: rick.handler.v1.EventEnvelope
	nil,                             // 19: rick.handler.v1.WorkflowNotification.TokensByPhaseEntry
	nil,                             // 20: rick.handler.v1.WorkflowNotification.TokensByBackendEntry
}
var file_internal_grpchandler_proto_handler_proto_depIdxs = []int32{
	1,  // 0: rick.handler.v1.HandlerMessage.registration:type_name -> rick.handler.v1.HandlerRegistration
	2,  // 1: rick.handler.v1.HandlerMessage.result:type_name -> rick.handler.v1.HandlerResult
	3,  // 2: rick.handler.v1.HandlerMessage.heartbeat:type_name -> rick.handler.v1.Heartbeat
	8,  // 3: rick.handler.v1.HandlerMessage.inject:type_name -> rick.handler.v1.InjectEventRequest
	12, // 4: rick.handler.v1.HandlerMessage.watch:type_name -> rick.handler.v1.WatchRequest
	13, // 5: rick.handler.v1.HandlerMessage.unwatch:type_name -> rick.handler.v1.UnwatchRequest
	10, // 6: rick.handler.v1.HandlerMessage.register_workflow:type_name -> rick.handler.v1.RegisterWorkflowRequest
	18, // 7: rick.handler.v1.HandlerResult.events:type_name -> rick.handler.v1.EventEnvelope
	6,  // 8: rick.handler.v1.DispatchMessage.ack:type_name -> rick.handler.v1.RegistrationAck
	7,  // 9: rick.handler.v1.DispatchMessage.dispatch:type_name -> rick.handler.v1.DispatchRequest
	9,  // 10: rick.handler.v1.DispatchMessage.inject_result:type_name -> rick.handler.v1.InjectEventResult
	14, // 11: rick.handler.v1.DispatchMessage.notification:type_name -> rick.handler.v1.WorkflowNotification
	11, // 12: rick.handler.v1.DispatchMessage.workflow_result:type_name -> rick.handler.v1.RegisterWorkflowResult
	5,  // 13: rick.handler.v1.DispatchMessage.displaced:type_name -> rick.handler.v1.DisplacedNotification
	18, // 14: rick.handler.v1.DispatchRequest.event:type_name -> rick.handler.v1.EventEnvelope
	18, // 15: rick.handler.v1.InjectEventRequest.event:type_name -> rick.handler.v1.EventEnvelope
	19, // 16: rick.handler.v1.WorkflowNotification.tokens_by_phase:type_name -> rick.handler.v1.WorkflowNotification.TokensByPhaseEntry
	20, // 17: rick.handler.v1.WorkflowNotification.tokens_by_backend:type_name -> rick.handler.v1.WorkflowNotification.TokensByBackendEntry
	15, // 18: rick.handler.v1.WorkflowNotification.phases:type_name -> rick.handler.v1.PhaseSummary
	16, // 19: rick.handler.v1.WorkflowNotification.verdicts:type_name -> rick.handler.v1.VerdictDetail
	17, // 20: rick.handler.v1.VerdictDetail.issues:type_name -> rick.handler.v1.IssueSummary
	0,  // 21: rick.handler.v1.PersonaService.HandleStream:input_type -> rick.handler.v1.HandlerMessage
	4,  // 22: rick.handler.v1.PersonaService.HandleStream:output_type -> rick.handler.v1.DispatchMessage
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_grpchandler_proto_handler_proto_init() }
func file_internal_grpchandler_proto_handler_proto_init() {
	if File_internal_grpchandler_proto_handler_proto != nil {
		return
	}
	file_internal_grpchandler_proto_handler_proto_msgTypes[0].OneofWrappers = []any{
		(*HandlerMessage_Registration)(nil),
		(*HandlerMessage_Result)(nil),
		(*HandlerMessage_Heartbeat)(nil),
		(*HandlerMessage_Inject)(nil),
		(*HandlerMessage_Watch)(nil),
		(*HandlerMessage_Unwatch)(nil),
		(*HandlerMessage_RegisterWorkflow)(nil),
	}
	file_internal_grpchandler_proto_handler_proto_msgTypes[4].OneofWrappers = []any{
		(*DispatchMessage_Ack)(nil),
		(*DispatchMessage_Dispatch)(nil),
		(*DispatchMessage_InjectResult)(nil),
		(*DispatchMessage_Notification)(nil),
		(*DispatchMessage_WorkflowResult)(nil),
		(*DispatchMessage_Displaced)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpchandler_proto_handler_proto_rawDesc), len(file_internal_grpchandler_proto_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpchandler_proto_handler_proto_goTypes,
		DependencyIndexes: file_internal_grpchandler_proto_handler_proto_depIdxs,
		MessageInfos:      file_internal_grpchandler_proto_handler_proto_msgTypes,
	}.Build()
	File_internal_grpchandler_proto_handler_proto = out.File
	file_internal_grpchandler_proto_handler_proto_goTypes = nil
	file_internal_grpchandler_proto_handler_proto_depIdxs = nil
}
