// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
