// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection():Promise<boolean>;

export function GetConfig():Promise<main.Config>;

export function Reconnect():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;
