package github

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/marconn/rick-event-driven-development/internal/event"
	"github.com/marconn/rick-event-driven-development/internal/eventbus"
	"github.com/marconn/rick-event-driven-development/internal/pluginstore"
)

// Reporter subscribes to terminal workflow events on the bus and posts
// consolidated PR comments on GitHub when a workflow completes or fails.
type Reporter struct {
	gh       *Client
	pstore   *pluginstore.Store
	ciPoller *CIPoller // optional: polls CI after successful workflows
	logger   *slog.Logger
}

// NewReporter creates a GitHub reporter.
func NewReporter(gh *Client, pstore *pluginstore.Store, logger *slog.Logger) *Reporter {
	return &Reporter{
		gh:     gh,
		pstore: pstore,
		logger: logger,
	}
}

// WithCIPoller attaches a CI poller that runs after successful workflow completions.
func (r *Reporter) WithCIPoller(p *CIPoller) *Reporter {
	r.ciPoller = p
	return r
}

// Start subscribes to terminal workflow events on the bus.
// Returns an unsubscribe function that removes both subscriptions.
func (r *Reporter) Start(bus eventbus.Bus) func() {
	unsub1 := bus.Subscribe(event.WorkflowCompleted, r.handleTerminal,
		eventbus.WithName("github-reporter"))
	unsub2 := bus.Subscribe(event.WorkflowFailed, r.handleTerminal,
		eventbus.WithName("github-reporter"))
	return func() { unsub1(); unsub2() }
}

// handleTerminal fires when a workflow reaches terminal state. Builds
// a PR comment from the ticket data and posts it to GitHub.
func (r *Reporter) handleTerminal(ctx context.Context, env event.Envelope) error {
	ticket, err := r.pstore.GetTicketByCorrelation(env.CorrelationID)
	if err != nil {
		r.logger.Error("github reporter: lookup ticket",
			slog.String("correlation", env.CorrelationID),
			slog.Any("error", err),
		)
		return nil // non-fatal: not all workflows have tickets
	}
	if ticket == nil {
		r.logger.Debug("github reporter: no ticket for correlation, skipping",
			slog.String("correlation", env.CorrelationID),
		)
		return nil
	}

	if ticket.PRNumber == 0 || ticket.Repo == "" {
		r.logger.Warn("github reporter: ticket has no PR info, skipping",
			slog.String("ticket", ticket.TicketID),
			slog.String("repo", ticket.Repo),
			slog.Int("pr_number", ticket.PRNumber),
		)
		return nil
	}

	status := "completed"
	if env.Type == event.WorkflowFailed {
		status = "failed"
	}
	comment := buildComment(ticket, status)

	owner, repo, ok := parseOwnerRepo(ticket.Repo)
	if !ok {
		r.logger.Error("github reporter: invalid repo format (expected owner/repo)",
			slog.String("repo", ticket.Repo),
		)
		return nil
	}

	prComment, err := r.gh.CreatePRComment(ctx, owner, repo, ticket.PRNumber, comment)
	if err != nil {
		r.logger.Error("github reporter: post PR comment",
			slog.String("ticket", ticket.TicketID),
			slog.Int("pr_number", ticket.PRNumber),
			slog.Any("error", err),
		)
		return nil // non-fatal: don't dead-letter on GitHub API failure
	}

	r.logger.Info("github reporter: PR comment posted",
		slog.String("ticket", ticket.TicketID),
		slog.Int("pr_number", ticket.PRNumber),
		slog.Int("comment_id", prComment.ID),
	)

	// After posting the PR comment, poll CI if enabled and workflow completed.
	if r.ciPoller != nil && status == "completed" {
		go r.ciPoller.PollAfterWorkflow(ctx, env.CorrelationID, ticket)
	}

	return nil
}

// buildComment creates a GitHub PR comment from ticket info and workflow status.
// Simplified version — full verdict-enriched comments will come once projections
// are wired through.
func buildComment(ticket *pluginstore.Ticket, status string) string {
	var b strings.Builder

	statusEmoji := ":white_check_mark:"
	if status != "completed" {
		statusEmoji = ":x:"
	}
	b.WriteString(fmt.Sprintf("## %s Rick AI Review — %s\n\n", statusEmoji, ticket.TicketID))
	b.WriteString(fmt.Sprintf("**Status:** %s\n\n", status))

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("_Generated by Rick for %s_\n", ticket.TicketID))

	return b.String()
}

func parseOwnerRepo(repo string) (owner, name string, ok bool) {
	parts := strings.SplitN(repo, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", false
	}
	return parts[0], parts[1], true
}
