// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApproveHint(arg1:string,arg2:string,arg3:string):Promise<main.ActionResult>;

export function CancelWorkflow(arg1:string,arg2:string):Promise<main.ActionResult>;

export function CheckConnection():Promise<boolean>;

export function ClearContext():Promise<string>;

export function DeleteMemory(arg1:string):Promise<boolean>;

export function GetConfig():Promise<main.Config>;

export function InjectGuidance(arg1:string,arg2:string,arg3:string):Promise<main.ActionResult>;

export function ListDeadLetters():Promise<Array<main.DeadLetterEntry>>;

export function ListEvents(arg1:string,arg2:number):Promise<Array<main.EventEntry>>;

export function ListMemories():Promise<Array<main.Memory>>;

export function ListWorkflows():Promise<Array<main.WorkflowSummary>>;

export function PauseWorkflow(arg1:string,arg2:string):Promise<main.ActionResult>;

export function PersonaOutput(arg1:string,arg2:string):Promise<main.PersonaOutput>;

export function PhaseTimeline(arg1:string):Promise<Array<main.PhaseEntry>>;

export function Reconnect():Promise<string>;

export function RejectHint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ActionResult>;

export function ResumeWorkflow(arg1:string,arg2:string):Promise<main.ActionResult>;

export function SaveMemory(arg1:string,arg2:string):Promise<main.Memory>;

export function SearchMemories(arg1:string):Promise<Array<main.Memory>>;

export function SendMessage(arg1:string):Promise<void>;

export function TokenUsageForWorkflow(arg1:string):Promise<main.TokenUsage>;

export function WorkflowStatus(arg1:string):Promise<main.WorkflowDetail>;

export function WorkflowVerdicts(arg1:string):Promise<Array<main.VerdictRecord>>;
