// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveHint(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApproveHint'](arg1, arg2, arg3);
}

export function CancelWorkflow(arg1, arg2) {
  return window['go']['main']['App']['CancelWorkflow'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function ClearContext() {
  return window['go']['main']['App']['ClearContext']();
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InjectGuidance(arg1, arg2, arg3) {
  return window['go']['main']['App']['InjectGuidance'](arg1, arg2, arg3);
}

export function ListDeadLetters() {
  return window['go']['main']['App']['ListDeadLetters']();
}

export function ListEvents(arg1, arg2) {
  return window['go']['main']['App']['ListEvents'](arg1, arg2);
}

export function ListMemories() {
  return window['go']['main']['App']['ListMemories']();
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function PauseWorkflow(arg1, arg2) {
  return window['go']['main']['App']['PauseWorkflow'](arg1, arg2);
}

export function PersonaOutput(arg1, arg2) {
  return window['go']['main']['App']['PersonaOutput'](arg1, arg2);
}

export function PhaseTimeline(arg1) {
  return window['go']['main']['App']['PhaseTimeline'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function RejectHint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RejectHint'](arg1, arg2, arg3, arg4);
}

export function ResumeWorkflow(arg1, arg2) {
  return window['go']['main']['App']['ResumeWorkflow'](arg1, arg2);
}

export function SaveMemory(arg1, arg2) {
  return window['go']['main']['App']['SaveMemory'](arg1, arg2);
}

export function SearchMemories(arg1) {
  return window['go']['main']['App']['SearchMemories'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function TokenUsageForWorkflow(arg1) {
  return window['go']['main']['App']['TokenUsageForWorkflow'](arg1);
}

export function WorkflowStatus(arg1) {
  return window['go']['main']['App']['WorkflowStatus'](arg1);
}

export function WorkflowVerdicts(arg1) {
  return window['go']['main']['App']['WorkflowVerdicts'](arg1);
}
